spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scta_db?createDatabaseIfNotExist=true
    username: scta
    password: scta
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true