spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: ${SPRING.ZIPKIN.BASEURL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICEURL.DEFAULTZONE}